config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  root 'users#new'

  resources :users, only: %i[new create destroy]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :bigint           not null, primary key
#  crypted_password :string(255)
#  email            :string(255)      not null
#  salt             :string(255)
#  username         :string(255)      not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#
class User < ApplicationRecord
  authenticates_with_sorcery!

  # 通常のバリデーション
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  # 条件付きバリデーション
  validates :password, length: { minimum: 6 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_back_or_to root_path, success: 'ログインしました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, success: 'ログアウトしました'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to login_path, success: 'ユーザーを作成しました'
    else
      flash.now[:danger] = 'ユーザー作成に失敗しました'
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, success: 'ユーザーを削除しました'
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    / このメタタグは一旦コピペ
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title CookNote
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.css" rel="stylesheet"
    link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"
    script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.js"

  body
    - if logged_in?
      = render 'shared/header'
    - else 
      = render 'shared/header_before_login'
    = render 'shared/flash_messages'
    = yield

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  .alert.alert-danger
    ul 
      - object.errors.full_messages.each do |msg|
        li = msg

app/views/shared/_flash_messages.html.slim
- flash.each do |message_type, message|
  div class=("alert alert-#{message_type}") = message

app/views/shared/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-white
  = link_to 'CookNote', root_path, class: 'navbar-brand'
  / 表示サイズによりメニューを非表示にし、メニューバーを実行
  button.navbar-toggler aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarTogglerDemo02" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  / メニューの表示内容（折り畳まれる）
  #navbarTogglerDemo02.collapse.navbar-collapse
    / 検索窓
    form.form-inline.my-2.my-lg-0.mr-auto
      input.form-control.mr-sm-2 placeholder="Search" type="search" /
      button.btn.btn-outline-success.my-2.my-sm-0 type="submit"  Search
    / リンク 
    ul.navbar-nav.mt-2.mt-lg-0
      li.nav-item
        a.nav-link href="#"
          = icon 'far', 'image', class: 'fa-lg'
      li.nav-item
        a.nav-link href="#"
          = icon 'far', 'heart', class: 'fa-lg'
      li.nav-item
        a.nav-link href="#"
          = icon 'far', 'user', class: 'fa-lg'
      li.nav-item
        = link_to 'ログアウト', logout_path, class: 'nav-link', method: :delete

app/views/shared/_header_before_login.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-white
  = link_to 'CookNote', root_path, class: 'navbar-brand'
  / 表示サイズによりメニューを非表示にし、メニューバーを実行
  button.navbar-toggler aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarTogglerDemo02" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  / メニューの表示内容（折り畳まれる）
  #navbarTogglerDemo02.collapse.navbar-collapse
    form.form-inline.my-2.my-lg-0.mr-auto
      / 検索窓
      input.form-control.mr-sm-2 placeholder="Search" type="search" /
      button.btn.btn-outline-success.my-2.my-sm-0 type="submit"  Search
    / 各種リンク
    ul.navbar-nav.mt-2.mt-lg-0
      li.nav-item
        = link_to 'レシピ一覧', '#', class: 'nav-link'
      li.nav-item
        = link_to 'ログイン', login_path, class: 'nav-link'

app/views/user_sessions/new.html.slim
.login-register-form 
  .login-register-form-inner
    .card.mb-3 
      .card-body
        = form_with url: login_path, local: true do |f|
          .form-group
            = f.label :email, 'メールアドレス'
            = f.email_field :email, class: 'form-control'
          .form-group
            = f.label :password, 'パスワード'
            = f.text_field :password, class: 'form-control'
          = f.submit 'ログイン', class: 'btn btn-primary'
    .card
      .card-body 
        | アカウントをお持ちでないですか？
        = link_to '登録する', new_user_path

app/views/users/destroy.html.slim
h1 Users#destroy
p Find me in app/views/users/destroy.html.slim

app/views/users/new.html.slim
.login-register-form 
  .login-register-form-inner
    .card.mb-3 
      .card-body
        = form_with model: @user, local: true do |f|
          = render 'shared/error_messages', object: @user
          .form-group
            = f.label :usename, 'ユーザー名'
            = f.text_field :username, class: 'form-control'
          .form-group
            = f.label :email, 'メールアドレス'
            = f.email_field :email, class: 'form-control'
          .form-group
            = f.label :password, 'パスワード'
            = f.text_field :password, class: 'form-control'
          .form-group
            = f.label :password_confirmation, 'パスワード（確認）'
            = f.text_field :password_confirmation, class: 'form-control'
          = f.submit '登録', class: 'btn btn-primary'
    .card
      .card-body 
        | アカウントをお持ちですか？
        = link_to 'ログインする', login_path